export const ActionTypes = {
  TOGGLE_BOTTOM_PANEL: "TOGGLE_BOTTOM_PANEL",
  TOGGLE_SIDE_PANEL: "TOGGLE_SIDE_PANEL",
  UPDATE_SEARCH_RESULTS: "UPDATE_SEARCH_RESULTS",
  SHOW_IN_SLIDE_PANEL: "SHOW_IN_SLIDE_PANEL",
  SET_USER: "SET_USER",
  UPDATE_SAVED_PINS: "UPDATE_SAVED_PINS",
  LOGIN: "LOGIN"
};

// export const TOGGLE_BOTTOM_PANEL = "TOGGLE_BOTTOM_PANEL";
// export const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";
// export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
// export const SHOW_IN_SLIDE_PANEL = "SHOW_IN_SLIDE_PANEL";
// export const SET_USER = "SET_USER";

// export const UPDATE_SAVED_PINS = "UPDATE_SAVED_PINS";

